// Copyright (c) 2019, Daniel Martí <mvdan@mvdan.cc>
// See LICENSE for licensing information

package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/kenshaw/ini"
)

// errCacheFailed is returned by cmdCache when one or more items fail to
// decrypt. The summary line (N/M items cached, K failed) has already been
// printed to stderr, so main1 must NOT print this error — it only uses it
// to select exit code 1.
var errCacheFailed = fmt.Errorf("cache failed")

// kdfInfo returns a diagnostic string describing the current KDF parameters.
// Used in decryption error messages so users can spot stale KDF blocks.
func kdfInfo() string {
	kdfType := "pbkdf2"
	if globalData.KDF == KDFTypeArgon2id {
		kdfType = "argon2id"
	}
	return fmt.Sprintf("kdf: %s, iter=%d, mem=%d, par=%d",
		kdfType, globalData.KDFIterations, globalData.KDFMemory, globalData.KDFParallelism)
}

func cmdCache(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("cache", flag.ContinueOnError)
	var configPath string
	var outputPath string
	var mirrorLibsecret string

	xdgRuntime := os.Getenv("XDG_RUNTIME_DIR")
	if xdgRuntime == "" {
		xdgRuntime = "/tmp"
	}
	defaultOutput := filepath.Join(xdgRuntime, "devbox-secrets.sh")

	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" {
		home, _ := os.UserHomeDir()
		configDir = filepath.Join(home, ".config")
	}
	defaultConfig := filepath.Join(configDir, "bitw", "cache.ini")

	fs.StringVar(&configPath, "config", defaultConfig, "path to cache manifest (INI)")
	fs.StringVar(&outputPath, "output", defaultOutput, "path to write cache file")
	fs.StringVar(&mirrorLibsecret, "mirror-libsecret", "", "comma-separated env vars to mirror to libsecret")

	if err := fs.Parse(args); err != nil {
		return err
	}

	// Load manifest.
	manifest, err := ini.LoadFile(configPath)
	if err != nil {
		return fmt.Errorf("could not load manifest %s: %w", configPath, err)
	}

	// Ensure we have a fresh access token and a freshly synced vault. Without
	// sync, the cipherIndex below would only see ciphers present in data.json
	// at startup — missing any created since (via `bitw create` or the web UI).
	// This makes `bitw cache` a true drop-in for the bash bin/secrets-refresh
	// wrapper (which did `bitw sync` as a preflight before its per-item loop).
	if err := ensureToken(ctx); err != nil {
		return err
	}
	if err := sync(ctx); err != nil {
		return err
	}

	// Unlock vault (derive master key via Argon2id/PBKDF2 — once).
	if _, err := secrets.password(); err != nil {
		return err
	}
	if err := secrets.initKeys(); err != nil {
		return err
	}

	// Build cipher name → Cipher index (one full scan, not per-item).
	cipherIndex := make(map[string]*Cipher)
	for i := range globalData.Sync.Ciphers {
		c := &globalData.Sync.Ciphers[i]
		if c.Login == nil {
			continue
		}
		name, err := secrets.decryptStr(c.Name, c.OrganizationID)
		if err != nil {
			continue
		}
		cipherIndex[name] = c
	}

	// Prepare atomic write: tmpfile in the same directory as output.
	outDir := filepath.Dir(outputPath)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("could not create output directory %s: %w", outDir, err)
	}
	tmp, err := os.CreateTemp(outDir, ".devbox-secrets-*.tmp")
	if err != nil {
		return fmt.Errorf("could not create temp file: %w", err)
	}
	tmpName := tmp.Name()
	cleanup := true
	defer func() {
		if cleanup {
			os.Remove(tmpName)
		}
	}()

	// Header.
	fmt.Fprintf(tmp, "# Auto-generated by bitw cache — do not edit by hand.\n")
	fmt.Fprintf(tmp, "# Generated at %s\n", time.Now().Format(time.RFC3339))

	var failures int
	var total int

	// [cache] section: cipher-name = ENV_VAR (password field).
	// Use RawKeys to preserve cipher-name case (the default KeyManipFunc
	// lowercases keys, which would break cipher names like
	// "Devbox-Global/GitHub-Token" → "devbox-global/github-token"). Note:
	// RawKeys returns keys with surrounding whitespace (the parser does
	// not trim them; only Keys applies the trimming KeyManipFunc), so we
	// must TrimSpace before using the key for cipherIndex lookup.
	cacheSection := manifest.GetSection("cache")
	if cacheSection != nil {
		for _, rawKey := range cacheSection.RawKeys() {
			key := strings.TrimSpace(rawKey)
			envVar := cacheSection.Get(key)
			total++

			cipher, ok := cipherIndex[key]
			if !ok {
				failures++
				fmt.Fprintf(os.Stderr, "bitw cache: %s: cipher not found in vault (%s, email from: %s)\n",
					key, kdfInfo(), secrets.emailSource())
				continue
			}

			password, err := secrets.decryptStr(cipher.Login.Password, cipher.OrganizationID)
			if err != nil {
				failures++
				fmt.Fprintf(os.Stderr, "bitw cache: %s: decrypt field password: %v (%s, email from: %s)\n",
					key, err, kdfInfo(), secrets.emailSource())
				continue
			}

			fmt.Fprintf(tmp, "export %s=%s\n", envVar, shellQuote(password))
		}
	}

	// [cache-fields] section: cipher-name = field1,field2,...
	// Same whitespace caveat as [cache]: RawKeys returns untrimmed keys;
	// we TrimSpace before the cipherIndex lookup.
	fieldsSection := manifest.GetSection("cache-fields")
	if fieldsSection != nil {
		for _, rawKey := range fieldsSection.RawKeys() {
			key := strings.TrimSpace(rawKey)
			fieldsStr := fieldsSection.Get(key)
			cipher, ok := cipherIndex[key]
			if !ok {
				continue
			}
			for _, fieldName := range strings.Split(fieldsStr, ",") {
				fieldName = strings.TrimSpace(fieldName)
				if fieldName == "" {
					continue
				}
				total++

				val, err := resolveField(cipher, fieldName)
				if err != nil {
					failures++
					fmt.Fprintf(os.Stderr, "bitw cache: %s: decrypt field %s: %v (%s, email from: %s)\n",
						key, fieldName, err, kdfInfo(), secrets.emailSource())
					continue
				}

				fmt.Fprintf(tmp, "export %s=%s\n", fieldName, shellQuote(val))
			}
		}
	}

	// [cache-aliases] section: ALIAS_VAR = SOURCE_VAR.
	// Use RawKeys/GetRaw to preserve the original case of alias variable
	// names (the default KeyManipFunc lowercases keys, which would break
	// shell variable names like GH_TOKEN → gh_token).
	aliasesSection := manifest.GetSection("cache-aliases")
	if aliasesSection != nil {
		for _, rawKey := range aliasesSection.RawKeys() {
			sourceVar := aliasesSection.GetRaw(rawKey)
			aliasVar := strings.TrimSpace(rawKey)
			if aliasVar == "" || !isValidShellIdent(aliasVar) {
				continue
			}
			fmt.Fprintf(tmp, "export %s=$%s\n", aliasVar, sourceVar)
		}
	}

	// Finalize atomic write: chmod 600 + rename.
	if err := tmp.Chmod(0o600); err != nil {
		return fmt.Errorf("could not chmod temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("could not close temp file: %w", err)
	}
	if err := os.Rename(tmpName, outputPath); err != nil {
		return fmt.Errorf("could not rename temp file to %s: %w", outputPath, err)
	}
	cleanup = false // rename succeeded; nothing to clean up

	cached := total - failures
	fmt.Fprintf(os.Stderr, "%d/%d items cached, %d failed\n", cached, total, failures)

	if failures > 0 {
		return errCacheFailed
	}
	if total == 0 {
		return errCacheFailed
	}

	// Mirror to libsecret (best-effort — failures warn but don't abort).
	if mirrorLibsecret != "" {
		mirrorLibsecretVars(mirrorLibsecret)
	}

	return nil
}

// mirrorLibsecretVars shells out to secret-tool for each comma-separated var.
// Failures are warned on stderr but never abort the cache command.
func mirrorLibsecretVars(vars string) {
	for _, v := range strings.Split(vars, ",") {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		cmd := exec.Command("secret-tool", "store",
			"--label=Bitwarden API key",
			"bitwarden", v, os.Getenv(v),
		)
		if out, err := cmd.CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not mirror %s to libsecret: %v %s\n",
				v, err, bytes.TrimSpace(out))
		}
	}
}
