// Copyright (c) 2019, Daniel Martí <mvdan@mvdan.cc>
// See LICENSE for licensing information

package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/kenshaw/ini"
)

// errCacheFailed is returned by cmdCache when one or more items fail to
// decrypt. The summary line (N/M items cached, K failed) has already been
// printed to stderr, so main1 must NOT print this error — it only uses it
// to select exit code 1.
var errCacheFailed = fmt.Errorf("cache failed")

// kdfInfo returns a diagnostic string describing the current KDF parameters.
// Used in decryption error messages so users can spot stale KDF blocks.
func kdfInfo() string {
	kdfType := "pbkdf2"
	if globalData.KDF == KDFTypeArgon2id {
		kdfType = "argon2id"
	}
	return fmt.Sprintf("kdf: %s, iter=%d, mem=%d, par=%d",
		kdfType, globalData.KDFIterations, globalData.KDFMemory, globalData.KDFParallelism)
}

func cmdCache(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("cache", flag.ContinueOnError)
	var configPath string
	var outputPath string
	var mirrorLibsecret string
	var timeout time.Duration

	xdgRuntime := os.Getenv("XDG_RUNTIME_DIR")
	if xdgRuntime == "" {
		xdgRuntime = "/tmp"
	}
	defaultOutput := filepath.Join(xdgRuntime, "devbox-secrets.sh")

	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" {
		home, _ := os.UserHomeDir()
		configDir = filepath.Join(home, ".config")
	}
	defaultConfig := filepath.Join(configDir, "bitw", "cache.ini")

	fs.StringVar(&configPath, "config", defaultConfig, "path to cache manifest (INI)")
	fs.StringVar(&outputPath, "output", defaultOutput, "path to write cache file")
	fs.StringVar(&mirrorLibsecret, "mirror-libsecret", "", "comma-separated env vars to mirror to libsecret")
	fs.DurationVar(&timeout, "timeout", 0, "abort the whole command after this duration (0 = no timeout); recommended for init-hook paths so a hung re-auth does not block shell startup")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}

	// Load manifest.
	manifest, err := ini.LoadFile(configPath)
	if err != nil {
		return fmt.Errorf("could not load manifest %s: %w", configPath, err)
	}

	// Ensure we have a fresh access token and a freshly synced vault. Without
	// sync, the cipherIndex below would only see ciphers present in data.json
	// at startup — missing any created since (via `bitw create` or the web UI).
	// This makes `bitw cache` a true drop-in for the bash bin/secrets-refresh
	// wrapper (which did `bitw sync` as a preflight before its per-item loop).
	if err := ensureToken(ctx); err != nil {
		return err
	}
	if err := sync(ctx); err != nil {
		return err
	}

	// Unlock vault (derive master key via Argon2id/PBKDF2 — once).
	if _, err := secrets.password(); err != nil {
		return err
	}
	if err := secrets.initKeys(); err != nil {
		return err
	}

	// Build cipher name → Cipher index (one full scan, not per-item).
	cipherIndex := make(map[string]*Cipher)
	for i := range globalData.Sync.Ciphers {
		c := &globalData.Sync.Ciphers[i]
		if c.Login == nil {
			continue
		}
		name, err := secrets.decryptStr(c.Name, c.OrganizationID)
		if err != nil {
			continue
		}
		cipherIndex[name] = c
	}

	// Prepare atomic write: tmpfile in the same directory as output.
	outDir := filepath.Dir(outputPath)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("could not create output directory %s: %w", outDir, err)
	}
	tmp, err := os.CreateTemp(outDir, ".devbox-secrets-*.tmp")
	if err != nil {
		return fmt.Errorf("could not create temp file: %w", err)
	}
	tmpName := tmp.Name()
	cleanup := true
	defer func() {
		if cleanup {
			os.Remove(tmpName)
		}
	}()

	// Header.
	fmt.Fprintf(tmp, "# Auto-generated by bitw cache — do not edit by hand.\n")
	fmt.Fprintf(tmp, "# Generated at %s\n", time.Now().Format(time.RFC3339))

	var failures int
	var total int

	// decrypted collects every (envVar, value) pair written to the cache
	// file by the [cache] and [cache-fields] sections. The --mirror-libsecret
	// flag then sources from this map (not os.Getenv) so the mirror sees
	// the actual decrypted value, not whatever happened to be in the
	// shell's environment. This is critical for the init-hook call path,
	// which runs `bitw cache --mirror-libsecret=...` before sourcing the
	// cache file — i.e. before any value is in the shell's env.
	decrypted := make(map[string]string)

	// [cache] section: cipher-name = ENV_VAR (password field).
	// Use RawKeys to preserve cipher-name case (the default KeyManipFunc
	// lowercases keys, which would break cipher names like
	// "Devbox-Global/GitHub-Token" → "devbox-global/github-token"). Note:
	// RawKeys returns keys with surrounding whitespace (the parser does
	// not trim them; only Keys applies the trimming KeyManipFunc), so we
	// must TrimSpace before using the key for cipherIndex lookup.
	cacheSection := manifest.GetSection("cache")
	if cacheSection != nil {
		for _, rawKey := range cacheSection.RawKeys() {
			key := strings.TrimSpace(rawKey)
			envVar := cacheSection.Get(key)
			total++

			cipher, ok := cipherIndex[key]
			if !ok {
				failures++
				fmt.Fprintf(os.Stderr, "bitw cache: %s: cipher not found in vault (%s, email from: %s)\n",
					key, kdfInfo(), secrets.emailSource())
				continue
			}

			password, err := secrets.decryptStr(cipher.Login.Password, cipher.OrganizationID)
			if err != nil {
				failures++
				fmt.Fprintf(os.Stderr, "bitw cache: %s: decrypt field password: %v (%s, email from: %s)\n",
					key, err, kdfInfo(), secrets.emailSource())
				continue
			}

			if envVar != "" {
				decrypted[envVar] = password
			}
			fmt.Fprintf(tmp, "export %s=%s\n", envVar, shellQuote(password))
		}
	}

	// [cache-fields] section: cipher-name = field1,field2,...
	// Same whitespace caveat as [cache]: RawKeys returns untrimmed keys;
	// we TrimSpace before the cipherIndex lookup.
	fieldsSection := manifest.GetSection("cache-fields")
	if fieldsSection != nil {
		for _, rawKey := range fieldsSection.RawKeys() {
			key := strings.TrimSpace(rawKey)
			fieldsStr := fieldsSection.Get(key)
			cipher, ok := cipherIndex[key]
			if !ok {
				continue
			}
			for _, fieldName := range strings.Split(fieldsStr, ",") {
				fieldName = strings.TrimSpace(fieldName)
				if fieldName == "" {
					continue
				}
				total++

				val, err := resolveField(cipher, fieldName)
				if err != nil {
					failures++
					fmt.Fprintf(os.Stderr, "bitw cache: %s: decrypt field %s: %v (%s, email from: %s)\n",
						key, fieldName, err, kdfInfo(), secrets.emailSource())
					continue
				}

				decrypted[fieldName] = val
				fmt.Fprintf(tmp, "export %s=%s\n", fieldName, shellQuote(val))
			}
		}
	}

	// [cache-aliases] section: ALIAS_VAR = SOURCE_VAR.
	// Use RawKeys/GetRaw to preserve the original case of alias variable
	// names (the default KeyManipFunc lowercases keys, which would break
	// shell variable names like GH_TOKEN → gh_token).
	aliasesSection := manifest.GetSection("cache-aliases")
	if aliasesSection != nil {
		for _, rawKey := range aliasesSection.RawKeys() {
			sourceVar := aliasesSection.GetRaw(rawKey)
			aliasVar := strings.TrimSpace(rawKey)
			if aliasVar == "" || !isValidShellIdent(aliasVar) {
				continue
			}
			fmt.Fprintf(tmp, "export %s=$%s\n", aliasVar, sourceVar)
		}
	}

	// Finalize atomic write: chmod 600 + rename.
	if err := tmp.Chmod(0o600); err != nil {
		return fmt.Errorf("could not chmod temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("could not close temp file: %w", err)
	}
	if err := os.Rename(tmpName, outputPath); err != nil {
		return fmt.Errorf("could not rename temp file to %s: %w", outputPath, err)
	}
	cleanup = false // rename succeeded; nothing to clean up

	cached := total - failures
	fmt.Fprintf(os.Stderr, "%d/%d items cached, %d failed\n", cached, total, failures)

	if failures > 0 {
		return errCacheFailed
	}
	if total == 0 {
		return errCacheFailed
	}

	// Mirror to libsecret (best-effort — failures warn but don't abort).
	if mirrorLibsecret != "" {
		mirrorLibsecretVars(mirrorLibsecret, decrypted)
	}

	return nil
}

// mirrorLibsecretVars shells out to secret-tool for each comma-separated var,
// sourcing values from `values` (the decrypted map populated by the [cache]
// and [cache-fields] loops) rather than from os.Getenv. Reading from the env
// would be wrong: cmdCache writes decrypted values to the output file but
// never to its own process environment, so the only callers' shell would have
// to source the cache file BEFORE this function runs. The init-hook path
// (`bin/init-hook:13-14`) does the opposite — mirror first, source second —
// which means os.Getenv would always return "" there. Sourcing from the
// `values` map avoids this hazard entirely.
//
// The libsecret attribute scheme maps each env var to a stable semantic
// name (e.g., `BW_CLIENTSECRET` → `api-key-secret`). The semantic names
// are what the bash init-hook fallback looks up (`bin/init-hook:20,24`),
// so the mirror must use them — not the env var name — or the round-trip
// silently breaks. (See ADR-0003 §Fallback for the handoff.)
//
// CRITICAL: `secret-tool store` reads the secret from STDIN, not from a
// positional argument. The store argv is `secret-tool store --label=X
// collection attribute` — exactly one attr pair, no trailing value
// (otherwise secret-tool would interpret the value as a dangling attribute
// name and read stdin EOF as an empty password). The mirror follows the
// same pattern as `storePasswordLibsecret` (`auth.go:323-325`): secret
// on stdin. The consumer (init-hook's `$(secret-tool lookup …)`)
// command-substitution strips the trailing newline for us, so no
// trailing-newline normalization is needed here.
//
// If a var was requested for mirror but does not appear in the manifest's
// decrypted values, we warn on stderr instead of silently writing an empty
// string to libsecret — an empty credential would clobber any previously-
// stored good value and is almost certainly a config error (typo in the
// manifest or in `--mirror-libsecret`).
//
// Failures are warned on stderr but never abort the cache command.
func mirrorLibsecretVars(vars string, values map[string]string) {
	for _, v := range strings.Split(vars, ",") {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		val, ok := values[v]
		if !ok {
			fmt.Fprintf(os.Stderr,
				"warning: --mirror-libsecret requested %q but it was not decrypted by this run; "+
					"check the manifest matches the var name and the cipher exists\n", v)
			continue
		}
		attr, ok := mirrorAttrFor(v)
		if !ok {
			// Unknown var with no semantic-attr mapping → write under the
			// env var name itself. The init-hook fallback won't be able to
			// retrieve it (it only knows api-key-secret / api-key-client-id),
			// so this is a dead write. Warn so the user knows their config
			// is missing a mapping.
			fmt.Fprintf(os.Stderr,
				"warning: --mirror-libsecret var %q has no semantic libsecret attribute mapping; "+
					"the bash init-hook fallback cannot retrieve it. Add a case in mirrorAttrFor.\n", v)
			attr = v
		}
		if out, err := shell.CombinedOutput([]byte(val), "secret-tool", "store",
			"--label=Bitwarden API key",
			"bitwarden", attr,
		); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not mirror %s to libsecret: %v %s\n",
				v, err, bytes.TrimSpace(out))
		}
	}
}

// mirrorAttrFor maps an env var name to its stable libsecret attribute name.
// The bash init-hook fallback (`bin/init-hook:20,24`) hard-codes
// `api-key-secret` / `api-key-client-id`; if the mirror wrote under
// `BW_CLIENTSECRET` / `BW_CLIENTID` instead, the fallback would never find
// what it stored (an attribute mismatch that was the source of a real
// orphan-pane regression). This map is the single source of truth for
// the mapping; keep it in sync with init-hook if you add new mirrored
// credentials.
func mirrorAttrFor(envVar string) (string, bool) {
	switch envVar {
	case "BW_CLIENTSECRET":
		return "api-key-secret", true
	case "BW_CLIENTID":
		return "api-key-client-id", true
	}
	return "", false
}
