// Copyright (c) 2019, Daniel Martí <mvdan@mvdan.cc>
// See LICENSE for licensing information

package main

import (
	"context"
	"fmt"
	"strings"
)

// completionCommands is the static list of top-level bitw commands.
var completionCommands = []string{
	"sync", "login", "dump", "get", "cache", "create",
	"edit", "status", "list", "completions", "config", "help",
}

// completionGetFlags is the static list of get flags and subcommand keywords.
var completionGetFlags = []string{
	"--env-name", "--json", "--field", "totp",
}

// cmdCompletions prints a shell completion script to stdout.
// No unlock, no network, no decryption — the generated scripts never
// invoke `bitw` itself, so they cannot trigger a master password prompt.
func cmdCompletions(_ context.Context, args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("usage: bitw completions bash|zsh|fish")
	}
	// Resolve the default config dir once in Go (honors CONFIG_DIR env var
	// and platform-specific paths like ~/Library/Application Support on macOS).
	// Embed this literal path into each script as the fallback when CONFIG_DIR
	// is not set at runtime.
	defaultDir, err := resolveConfigDir()
	if err != nil {
		return fmt.Errorf("could not resolve config dir: %w", err)
	}
	switch args[0] {
	case "bash":
		fmt.Print(bashCompletionScript(defaultDir))
	case "zsh":
		fmt.Print(zshCompletionScript(defaultDir))
	case "fish":
		fmt.Print(fishCompletionScript(defaultDir))
	default:
		return fmt.Errorf("usage: bitw completions bash|zsh|fish")
	}
	return nil
}

func bashCompletionScript(defaultDir string) string {
	commands := strings.Join(completionCommands, " ")
	getOpts := strings.Join(completionGetFlags, " ")
	return fmt.Sprintf(`# bitw bash completion
# Generated by: bitw completions bash
_bitw() {
	local cur
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"

	if [[ $COMP_CWORD -eq 1 ]]; then
		COMPREPLY=($(compgen -W "%s" -- "$cur"))
		return
	fi

	case "${COMP_WORDS[1]}" in
		get)
			local names_file="${CONFIG_DIR:-%s}/names"
			if [[ -f "$names_file" ]]; then
				local name
				while IFS= read -r name; do
					[[ "$name" == "$cur"* ]] && COMPREPLY+=("$name")
				done < "$names_file"
			fi
			COMPREPLY+=($(compgen -W "%s" -- "$cur"))
			;;
		edit)
			local names_file="${CONFIG_DIR:-%s}/names"
			if [[ -f "$names_file" ]]; then
				local name
				while IFS= read -r name; do
					[[ "$name" == "$cur"* ]] && COMPREPLY+=("$name")
				done < "$names_file"
			fi
			;;
	esac
}
complete -F _bitw bitw
`, commands, defaultDir, getOpts, defaultDir)
}

func zshCompletionScript(defaultDir string) string {
	commands := strings.Join(completionCommands, " ")
	getOpts := strings.Join(completionGetFlags, " ")
	return fmt.Sprintf(`# bitw zsh completion
# Generated by: bitw completions zsh
_bitw() {
	local -a commands
	commands=(%s)

	if (( CURRENT == 2 )); then
		_describe 'command' commands
		return
	fi

	case "$words[2]" in
		get)
			local names_file="${CONFIG_DIR:-%s}/names"
			if [[ -f "$names_file" ]]; then
				local -a names
				names=(${(f)"$(<"$names_file")"})
				compadd -a names
			fi
			local -a get_opts
			get_opts=(%s)
			compadd -a get_opts
			;;
		edit)
			local names_file="${CONFIG_DIR:-%s}/names"
			if [[ -f "$names_file" ]]; then
				local -a names
				names=(${(f)"$(<"$names_file")"})
				compadd -a names
			fi
			;;
	esac
}

_bitw "$@"
`, commands, defaultDir, getOpts, defaultDir)
}

func fishCompletionScript(defaultDir string) string {
	commands := strings.Join(completionCommands, " ")
	getOpts := strings.Join(completionGetFlags, " ")
	return fmt.Sprintf(`# bitw fish completion
# Generated by: bitw completions fish

function __bitw_names
	set -l names_file "${CONFIG_DIR:-%s}/names"
	if test -f "$names_file"
		cat "$names_file"
	end
end

complete -c bitw -n '__fish_use_subcommand' -a '%s'
complete -c bitw -n '__fish_seen_subcommand_from get' -a '%s'
complete -c bitw -n '__fish_seen_subcommand_from get' -a "(__bitw_names)"
complete -c bitw -n '__fish_seen_subcommand_from edit' -a "(__bitw_names)"
`, defaultDir, commands, getOpts)
}
